CREATE TABLE "Roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(30) NOT NULL
);

CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(30) NOT NULL
);

CREATE TABLE "Courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" varchar(30) NOT NULL,
  "Description" varchar(300) NOT NULL,
  "Categories_id" int NOT NULL
);

CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" varchar(30) NOT NULL,
  "Email" varchar(30) NOT NULL,
  "Password" varchar(30) NOT NULL,
  "Age" int NOT NULL,
  "Roles_id" int NOT NULL
);

CREATE TABLE "Courses_Videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" varchar(30) NOT NULL,
  "Url" varchar(30) NOT NULL,
  "Courses_id" int NOT NULL
);

CREATE TABLE "Users_Courses" (
  "Users_id" int NOT NULL,
  "Courses_id" int NOT NULL
);

ALTER TABLE "Users_Courses" ADD FOREIGN KEY ("Users_id") REFERENCES "Users" ("id");

ALTER TABLE "Users_Courses" ADD FOREIGN KEY ("Courses_id") REFERENCES "Courses" ("id");

ALTER TABLE "Users" ADD FOREIGN KEY ("Roles_id") REFERENCES "Roles" ("id");

ALTER TABLE "Courses" ADD FOREIGN KEY ("Categories_id") REFERENCES "Categories" ("id");

ALTER TABLE "Courses_Videos" ADD FOREIGN KEY ("Courses_id") REFERENCES "Courses" ("id");

INSERT INTO "Categories" ("Name")
VALUES 
('Fundamentals'),
('React.js'),
('Node.js');

INSERT INTO "Roles" ("Name")
VALUES 
('Student'),
('Teacher'),
('Administrator');

INSERT INTO "Courses" ("Title", "Description", "Categories_id")
VALUES 
('Start of Fundamentals', 'Basic principles of HTML5, CSS3, and JavaScript', 1),
('Start of React.JS', 'Principles and fundamentals of React.JS', 2),
('Start of Node.JS', 'Principles and fundamentals of Node.JS', 3);

INSERT INTO "Users" ("Name", "Email", "Password", "Age", "Roles_id")
VALUES 
('Steven Contreras', 'steven@mail.com','123456789', 27, 1),
('Mauricio Castellanos', 'mauricio@mail.com','123456789', 30, 2),
('Jonathan Garcia', 'jonathan@mail.com','123456789', 29, 3);

INSERT INTO "Courses_Videos" ("Title", "Url", "Courses_id")
VALUES 
('Fundamentals class 1', 'This is a URL eg: 1', 1),
('React.JS class 1', 'This is a URL eg: 2', 2),
('Node.JS class 1', 'This is a URL eg: 3', 3);

INSERT INTO "Users_Courses" ("Users_id", "Courses_id")
VALUES 
(1, 3),
(2, 2),
(3, 1);

SELECT * FROM "Categories";

SELECT * FROM "Roles";

SELECT * FROM "Courses";

SELECT * FROM "Users";

SELECT * FROM "Courses_Videos";

SELECT * FROM "Users_Courses";